# Generated by Django 4.2.1 on 2023-05-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='post_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
