/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["empty"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthUser: {
            /** @example nilsmf */
            id: string;
            /** @description Hashed password */
            pwd: string;
        };
        /** @description Email struct, an email is verified to be existing and valid. */
        Email: string;
        /** @description Runtime of a service */
        Runtime: {
            /**
             * @description Date the service started
             * @example 11.03.24 [16:34]
             */
            date: string;
            /**
             * @description Time since epoch, in milliseconds
             * @example 69420
             */
            time: number;
        };
        User: {
            email: components["schemas"]["Email"];
            /** @description User identity */
            id: string;
            /** @description Internal ID, used in databases */
            iid: number;
        };
        /** @description Semver */
        Version: {
            /** @example 4 */
            major: number;
            /** @example 2 */
            minor: number;
            /** @example 0 */
            patch: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    empty: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description IGNORE */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
