# syntax=docker/dockerfile:1

# Base image
FROM python:3.11-slim-buster

# Set working directory
WORKDIR /app

# Copy requirements file
COPY pyreqs.txt .

# Install dependencies
RUN pip install --no-cache-dir -r pyreqs.txt

# Copy Django backend files
COPY djangobackend/ .

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=myapp.settings.production

# Expose port 8000
EXPOSE 8000

# Start Django backend server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
