# Generated by Django 4.2.1 on 2023-05-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_article_published_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
