# Generated by Django 4.2.1 on 2023-05-10 18:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_delete_article_delete_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('is_video', models.BooleanField()),
                ('description', models.CharField(max_length=150)),
                ('media', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('is_published', models.BooleanField()),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('last_updated', models.DateField(blank=True)),
                ('author_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.author')),
                ('body_media_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_media', to='media.media')),
                ('frontpage_media_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontpage_media', to='media.media')),
            ],
        ),
    ]
