# Generated by Django 4.2.1 on 2023-05-10 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_alter_article_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
